[build]
# Railway a veces ignora root para monorepos; forzamos comandos que operan dentro de backend/
buildCommand = "npm --prefix backend install && npm --prefix backend run build"

[deploy]
startCommand = "npm --prefix backend run start"
healthcheckPath = "/ping"
healthcheckTimeout = 60
restartPolicyType = "on_failure"

# NOTA IMPORTANTE:
# El script postinstall en backend/package.json ejecuta sync:all + seed (BORRA Y RECREA TABLAS)
# Para producción elimina ese postinstall o condiciona con: `if [ \"$NODE_ENV\" != \"production\" ]; then npm run sync:all && npm run seed; fi`.
